### PR TITLE
Fix install location of pkgconfig file

### PR DESCRIPTION
**Pull request by daissi**
This file contains architecture specific dir (for instance on `x86_64` : `libdir=/usr/lib/x86_64-linux-gnu`), so it needs to be installed in a multi-arch path. This patch is applied in the [debian package](https://salsa.debian.org/multimedia-team/openfec/-/blob/master/debian/patches/Fix_install_pkgconfig.patch).

### CODE REVIEW

**Comment by gavv** [comment]
Thanks!

Can we use `CMAKE_INSTALL_FULL_LIBDIR` instead of `CMAKE_INSTALL_LIBDIR` for consistency with the rest cmake scripts?

**Comment by gavv** [comment]
I've changed it to `CMAKE_INSTALL_FULL_LIBDIR`, but let me know if we need to revert it.

**Comment by gavv** [comment]
Tagged new release: https://github.com/roc-streaming/openfec/releases/tag/v1.4.2.11

**Comment by daissi** [comment]
> I've changed it to `CMAKE_INSTALL_FULL_LIBDIR`, but let me know if we need to revert it.

Thanks! It works too!

**Pull request merged**
